#!/usr/bin/env bash
# Configures nginx to add a redirect

apt-get update -y
apt-get install nginx -y

# Create redirect config
sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Start or reload nginx
service nginx start || service nginx reload
