#!/usr/bin/env bash
# Configures nginx to use a custom 404 page

apt-get update -y
apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update nginx config
sed -i '/server_name _;/a \\n    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        internal;\n    }' /etc/nginx/sites-available/default

# Start or reload nginx
service nginx start || service nginx reload
